### ISSUE TITLE
REQ REP with Q lengths of 0 allow sends without recv

### ISSUE THREAD

**Issue by vrecan** [go-mangos/mangos#180] opened 2016-02-13 00:44 UTC
If I do something really simple like create a request reply where I start sending before I recv messages with recv and write q's of 0 I would expect that my sends would fail until my recv is called. What I actually get is the ability to send exactly 2 messages. This is using inproc. When I switch to tcp it allows me to send 5609 messages... on the 5610 message it finally starts to timeout. 

Is this expected behavior? This seems odd if I have no buffer where are these messages going?

**Comment by gdamore** [comment] 2016-02-13 01:05
You need to understand that what we are dealing with is a queue *before* the "operating system send queue".

In the case of inproc, there isn't one.  So you get some basic tiny queuing from asynchronous delivery, but that's it.  (Basically the far end picks up the messages and then doesn't quite finish delivering to the recv because... you've not called it yet.)  inproc has no message size, so you're going to see it stall up on 2 messages regardless of message size, I theorize.

TCP is quite different.  In this case we deliver a message to the TCP stream.  The operating system on both ends has a certain amount of buffering.  So we can deliver those messages to TCP without blocking, until the TCP pipe fills up.  Since these are tiny messages (a few bytes for the zero length header really), you can send quite a lot of them.

The fact that your *application* hasn't received them yet really, really underscores why you don't want to assume that any "delivery" success (returning without error) means anything.  All it means is that you've got the messages out the door... it means nothing for application receipt -- you need message acknowledgment for that.  Understanding why  idempotency is a very good thing un this situation is left as an exercise for the reader. :-)

It would be interesting to try to figure out how the 5609/5610 balance works out.  We send initial TCP connection header of 8 bytes, then for each message we send a length header of 8-bytes.  For REQ protocol messages, we send a REQ header which is 4 bytes, but each additional hop adds 4 more bytes to the header.  So the minimum TCP message size is 12 bytes.  This isn't very very different from a 64k window size (5610*12).  By the time you wind up adding message framing within TCP itself, you might find that you're close to that value. 

Fun stuff to think about. :-)

**Comment by gdamore** [comment] 2016-02-15 23:39
Closing this since its not a bug.

**Closed by gdamore** 2016-02-15 23:39 UTC

**Comment by vrecan** [comment] 2016-02-16 15:38
Thanks for the great explanation. This was the same behavior I saw with ZMQ as well. I really wish we had some simple synchronous push queue similar to a 0 length buffer channel in go. This is extremely useful when writing clustered software.

What happens if you send a REQ to something then don't read the reply and move on. If I close the REQ socket does the reply to that always live in the REP's queue? If this happens a lot would I eventually block because of the REP's queue being full?

**Comment by gdamore** [comment] 2016-02-16 15:49
REP messages are delivered on a best effort basis. If the pipe is itself unavailable then the  reply is discarded. This is necessary because it would be incorrect to send the reply to any other pipe than the one the request arrived from.

**Comment by vrecan** [comment] 2016-02-16 19:00
That's good. Thanks for your help.
