### ISSUE TITLE
pubsub: mangos drops insane amount of messages

### ISSUE THREAD

**Issue by OneOfOne** [go-mangos/mangos#186] opened 2016-03-29 01:18 UTC
I found this bug after a colleague and I have been hitting our heads against the wall for a while.

The code is [here](https://gist.github.com/OneOfOne/ac141c675b7942186769), uncomment the `log.Printf("missed %d, got %d", i, v)` line to see the amount of dropped messages.

**Comment by itsmontoya** [comment] 2016-03-29 04:50
Here are some results from my testing:
```
## Message count: 2,000,000

### Library-provided example
Test #1 - 104,781 received
Test #2 - 112,135 received
Test #3 - 110,420 received

### 1ms delay added after each Publish
Test #1 - 2,000,000 received
Test #2 - 2,000,000 received
Test #3 - 2,000,000 received
```

**Comment by itsmontoya** [comment] 2016-03-29 05:20
I found 100,000ns (.1ms) seems to be the sweet spot where messages stop dropping off. Will provide some updated stats shortly.

**Comment by gdamore** [comment] 2016-03-29 09:44
This is totally expected. You are trying to publish messages faster than they can be delivered.  As there is no pushback with pub sub mangos drops them on the floor. (Pushback cannot be used with a multicast pattern like pub sub or you would have a situation where a single slow subscriber could gum up all the others. So we instead use a best effort approach and drop the messages when TCP cannot accommodate them.

Slowing down your publish rate so that the receiver and the transport can keep up solves this problem as you have noted. 

A consequence of this is that pub sub is probably not suited to very message rates. This is a problem in general for multicast protocols. 

I'm closing this as not a bug as mangos is performing as designed here.

**Closed by gdamore** 2016-03-29 09:44 UTC

**Comment by gdamore** [comment] 2016-03-29 09:46
Btw ensuring that your subscriber runs on a seperate OS thread ideally at higher priority will also help.
