### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Arhius** [go-mangos/mangos#276] opened 2017-05-24 14:25 UTC
Hello
I have an issue with pub/sub model. I have one publisher that listen to ip:5556 and 4 workers(subs) that dial to ip:5556. After few hour of test work the usage of used memory increased. Can You please recommend me how can I solve such problem? 
My code
type Publisher struct {
	sync.RWMutex
	pub mangos.Socket
}

func GatherSyncData(ip string, cache *ccache.Cache) {

	subscriber := GetSubscriber(ip)

	for {
		subscriber.Lock()
		message, err := subscriber.pub.Recv()
		subscriber.Unlock()
		if err != nil {
			log.Println(err)
			continue
		}

		go SeveSyncUUID(string(message), cache)
	}
}

func SeveSyncUUID(msg string, cache *ccache.Cache) {

	glink := strings.Split(msg, "|")

	cache.Set(glink[0], glink[1], time.Minute*10)
}

func GetPublisher() Publisher {
	socket, err := pub.NewSocket()

	if err != nil {
		log.Println(err)
		return Publisher{pub: nil}
	}

	socket.AddTransport(tcp.NewTransport())
	err = socket.Listen(fmt.Sprintf("tcp://%s:5556", *ip))

	if err != nil {
		log.Println(err)
		return Publisher{pub: nil}
	}

	socket.SetOption(mangos.OptionSendDeadline, time.Second*1)

	return Publisher{pub: socket}
}

func GetSubscriber(worker string) Publisher {
	socket, err := sub.NewSocket()
	socket.SetOption(mangos.OptionSubscribe, []byte(worker))

	if err != nil {
		log.Println(err)
		return Publisher{pub: nil}
	}

	socket.AddTransport(tcp.NewTransport())
	err = socket.Dial(fmt.Sprintf("tcp://%s:5556", worker))

	if err != nil {
		log.Println(err)
		return Publisher{pub: nil}
	}
	return Publisher{pub: socket}
}

**Comment by gdamore** [comment] 2017-05-24 17:36
It looks to me like SeveSyncScreen is responsible for leaking the strings into the cache?

Other than that, do you have any more data about *what* data you think is leaking?

**Comment by Arhius** [comment] 2017-05-26 09:55
I have checked everything one more time. Everything seems right. But I have one more question about connections. My pub/sub code now working infinitely. After starting of pub and subs they are newer close and unsubscribe because there are approximately 500 messages per second. Is it right for keeping connection forever. Can it be a cause of memory leak?

**Comment by gdamore** [comment] 2017-07-16 16:35
sorry didnt see this. yes we keep the connection open until one of the
sides closes it. no this isnt a leak.

**Comment by gdamore** [comment] 2017-11-15 14:33
You might also look at https://github.com/go-mangos/mangos/pull/285

I think that PR found some actual leaks.  Not sure if you're seeing that or not, but I hope to merge that today.

**Comment by gdamore** [comment] 2017-12-26 19:26
I'm closing this -- it's not a bug.

**Closed by gdamore** 2017-12-26 19:26 UTC
