### ISSUE TITLE
quick questions / managing and scaling the scalability :-)

### ISSUE THREAD

**Issue by roscopecoltran** [go-mangos/mangos#271] opened 2017-02-02 11:07 UTC
Hi,

Just quick questions about go-mangos about what would be the best way **to build a gateway service**, like [krakend](https://github.com/devopsfaith/krakend) , **and use the different set of surveyor/respondents services per routes defined in the gateway** ?

eg workflow:
![krakend-gateway](https://cloud.githubusercontent.com/assets/24416962/22546996/c0dce962-e93f-11e6-8819-649e2e4ab956.png)

**In my case it can also be, and more often, a multi-part form as an input, submitting an image JPEG/PNG with some POST data ?**

So my questions are:

1. What would be the best messaging strategy for building a gateway with the surveyor protocol sending a request to variable respondent services and expect an aggregate JSON response ? 

2. How to manage the service trees dynamically if a pre-processing step failed or is discarded ? Maybe by saving the respondents host:ports in [etcd](https://github.com/coreos/etcd) ?

3. Are tools like [red-node](https://github.com/node-red/node-red), [cascades](https://github.com/cascades-fbp/cascades), or [goflow](https://github.com/trustmaster/goflow), [noflo](https://noflojs.org/noflo-ui/) the closest road to build such distrubution patterns for go-mangos graphically ? 

4. What would be the best serialization package to use with go-mangos and the surveyor protocol (msgpck, cap n proto) ?

5. Is it possible to use websockets with the surveyor protocol ?

Thanks !

Have a great day !

Richard

**Comment by gdamore** [comment] 2017-02-02 18:30
You've asked a number of questions, and I don't have answers for them all.

1. This question is so generally broad I'm not sure.   You'd probably write some custom code for the surveyor to aggregate your responses, and then you can either store them for answer back to a REQ/REP or process them however else you'd like.

2. I don't think there's a single right answer here.  I've not used etcd in this particular fashion.  I think most folks that use mangos service discovery do that *instead* of using etcd or consul.  The thing is that the surveyor protocol doesn't actually build any trees for you -- you have to do that yourself -- it's just collecting survey responses; what you do with them is entirely up to you.

3. Sadly I don't have experience with any of those named tools.  Maybe someone else on the list does.

4. I've had good experience with msgpack, and with protocol buffers, over mangos.  My next project that needs serialization will probably use this: https://github.com/glycerine/zebrapack  -- which is just some refinements on msgpack to add something like an IDL.  There are many considerations when choosing a serialization protocol, and there isn't a single right answer.  Do you need / want an IDL?  What interoperability concerns do you have?  Do you need to store to disk as well?  What's more important, minimizing space/bandwidth or minimizing compute cycles?

5. Yes.  However, be advised that the protocol requires the websocket peer to understand the specific framing that we use in addition to websocket -- essentially we have a small header that has to be included in the websocket payload.  Please see the surveyor pattern RFCs for that.  (The need for the headers used by REQ/REP and SURVEYOR/RESPONDENT is one of the biggest sticking points for people trying to use browser based websockets; they're used to just using PAIR which has no additional headers.)

**Comment by gdamore** [comment] 2017-03-17 02:54
This was a question, not a bug.  Closing.

**Closed by gdamore** 2017-03-17 02:54 UTC
