### ISSUE TITLE
benchmarks correct?

### ISSUE THREAD

**Issue by nkev** [go-mangos/mangos#179] opened 2016-01-26 08:59 UTC
Mangos benchmarks just run on:
MacBook Pro (Retina, 15-inch, Late 2013) 
2.6 GHz Intel Core i7 
16 GB 1600 MHz DDR3
OSX El Capitan 10.11.2

Benchmark | Iterations | ns/ops | MB/s 
--- | --- | --- | ---
BenchmarkLatencyInp-8 | 200000 | 5815 ns/op | n/a
BenchmarkLatencyIPC-8 | 50000 | **24892** ns/op | n/a
BenchmarkLatencyTCP-8 | 30000 | 45610 ns/op | n/a
BenchmarkLatencyTLS-8 | 30000 | 54154 ns/op | n/a
BenchmarkLatencyWS-8 | 50000 | 38786 ns/op | n/a
BenchmarkLatencyWSS-8 | 30000 | 45730 ns/op | n/a
BenchmarkTPut4kInp-8 | 500000 |  3623 ns/op | 1130.28 MB/s
BenchmarkTPut4kIPC-8 | 200000 | 6493 ns/op | 630.81 MB/s
BenchmarkTPut4kTCP-8 | 200000 | 9654 ns/op | 424.27 MB/s
BenchmarkTPut4kTLS-8 | 200000 | 7509 ns/op | 545.43 MB/s
BenchmarkTPut4kWS-8 | 200000 | **6415** ns/op | 638.42 MB/s
BenchmarkTPut4kWSS-8 | 200000	 | 7617 ns/op | 537.72 MB/s
BenchmarkTPut64kInp-8 | 50000 | **25661** ns/op | 2553.83 MB/s
BenchmarkTPut64kIPC-8 | 100000	 | 12234 ns/op | 5356.67 MB/s
BenchmarkTPut64kTCP-8 | 100000 | 12751 ns/op | 5139.28 MB/s
BenchmarkTPut64kTLS-8 | 100000 | **12014** ns/op | 5454.72 MB/s
BenchmarkTPut64kWS-8 | 100000 | 13063 ns/op | 5016.88 MB/s
BenchmarkTPut64kWSS-8 | 100000 | 11794 ns/op | 5556.39 MB/s

Questions:
1) Does IPC have significantly better latency than TCP on Linux (as it does on Mac above)?

2) I thought WS was a layer on top of TCP. Why would WS have less latency and also perform better on 4K payloads than TCP?

3) For 64K payloads, why would INPROC perform worse than all the other external protocols? Does this mean Go channels have slower throughput than TCP for 64k payloads?

4) Why would TLS be more performant than TCP in both 4k and 64k tests?

Please enlighten me :)

**Comment by nkev** [comment] 2016-02-25 03:48
anyone?

**Comment by gdamore** [comment] 2016-02-25 05:33
IPC is almost certainly lower latency.  But it may perform worse for larger messages due to limits in the OS.  I've not measured this on Linux. 

Websocket is makes use of optimizations in the http layer and probably sends fewer messages. Nagle may play a role here as due to the lack of TCP CORK I wind up sending two messages - one for the header and again for the data. Fixing this is a goal and I have some ideas. Data copying might be the answer for small frames. 

Inproc is not highly optimized and does extra data copies. I don't consider its performance to be a major goal since there is little reason to use it in real apps. You'd just use channels for intra process comms in go.  That said there are probably ways it could be made faster.

**Comment by Term1nal** [comment] 2016-02-27 06:51
I've imagined a possible practical reason why someone may wish to use Inproc.

It's observable that when prototyping the start of a system based around microservices, It may be easier to reason about an initial system if first built as a modularized monolith then split it apart when the size and separation of concerns of the individual modules are satisfactorily determined.

Using inproc as the transport initially, then splitting the modules separated by the mangos inproc sockets off to separate processes/hosts then just changing the transport type might be an easy way to bootstrap the design of a microservice based system.

Just an idea. :3

**Comment by nkev** [comment] 2016-02-27 07:02
@Term1nal That's exactly what I'm toying around with! :) However, I'm not sure if Mangos is stable or supported enough. As stated in unanswered #178, I've also been losing messages butI'm not proficient enough in Go to fix it.

**Comment by gdamore** [comment] 2016-04-28 21:07
So #178 was not a bug, Mangos drops messages on congestion, by design.

The IPC performance is going to suck on many systems with large messages, because the message must be delivered a small bit at a time, due to pipe buffer limitations.  This causes a much larger number of system calls (and context switches).  For small messages IPC will out perform TCP, I think.

With respect to inproc performance, I'm happy with the performance now.  The use case (prototyping) is fine, and doesn't justify huge effort to optimize since that's not a typical production case.

Closing this.

**Closed by gdamore** 2016-04-28 21:07 UTC
