### ISSUE TITLE
REQREP bug: sock.Recv() send message two times

### ISSUE THREAD

**Issue by mrLSD** [go-mangos/mangos#299] opened 2017-12-20 11:07 UTC
After updating to new version of go-mangos and many test I found a bug - when Listen new message and invoke sock.Recv() I got two same messages.

Example code and log below.

```
// To use:
//
//   $ go build .
//   $ url=tcp://127.0.0.1:40899
//   $ ./reqrep node0 $url & node0=$! && sleep 1
//   $ ./reqrep node1 $url
//   $ kill $node0
//
package main

import (
	"fmt"
	"github.com/go-mangos/mangos"
	"github.com/go-mangos/mangos/protocol/rep"
	"github.com/go-mangos/mangos/protocol/req"
	"github.com/go-mangos/mangos/transport/ipc"
	"github.com/go-mangos/mangos/transport/tcp"
	"os"
	"time"
)

func die(format string, v ...interface{}) {
	fmt.Fprintln(os.Stderr, fmt.Sprintf(format, v...))
	os.Exit(1)
}

func date() string {
	return time.Now().Format(time.ANSIC)
}

func node0(url string) {
	var sock mangos.Socket
	var err error
	var msg []byte
	if sock, err = rep.NewSocket(); err != nil {
		die("can't get new rep socket: %s", err)
	}
	sock.AddTransport(ipc.NewTransport())
	sock.AddTransport(tcp.NewTransport())
	if err = sock.Listen(url); err != nil {
		die("can't listen on rep socket: %s", err.Error())
	}
	for {
		// Could also use sock.RecvMsg to get header
		msg, err = sock.Recv()
			fmt.Println("NODE0: RECEIVED DATE REQUEST:", string(msg))
			d := date()
			err = sock.Send([]byte(d))
			fmt.Printf("NODE0: SENDING DATE %s %+v\n", d, err)
			if err != nil {
				die("can't send reply: %s", err.Error())
			}
	}
}

func node1(url string) {
	var sock mangos.Socket
	var err error
	var msg []byte

	if sock, err = req.NewSocket(); err != nil {
		die("can't get new req socket: %s", err.Error())
	}
	sock.AddTransport(ipc.NewTransport())
	sock.AddTransport(tcp.NewTransport())
	if err = sock.Dial(url); err != nil {
		die("can't dial on req socket: %s", err.Error())
	}

	date := time.Now().Format(time.RFC3339)
	fmt.Printf("NODE1: SENDING DATE REQUEST %s\n", date)
	if err = sock.Send([]byte(date)); err != nil {
		die("can't send message on push socket: %s", err.Error())
	}
	if msg, err = sock.Recv(); err != nil {
		die("can't receive date: %s", err.Error())
	}
	fmt.Printf("NODE1: RECEIVED DATE %s\n", string(msg))
	sock.Close()
}

func main() {
	if len(os.Args) > 2 && os.Args[1] == "node0" {
		node0(os.Args[2])
		os.Exit(0)
	}
	if len(os.Args) > 2 && os.Args[1] == "node1" {
		node1(os.Args[2])
		os.Exit(0)
	}
	fmt.Fprintf(os.Stderr, "Usage: reqrep node0|node1 <URL>\n")
	os.Exit(1)
}

```

Response log:
```
$ ./reqrep node0 $url
NODE0: RECEIVED DATE REQUEST: 2017-12-19T19:44:12+02:00
NODE0: SENDING DATE Tue Dec 19 19:44:12 2017 <nil>
NODE0: RECEIVED DATE REQUEST: 2017-12-19T19:44:12+02:00
NODE0: SENDING DATE Tue Dec 19 19:44:12 2017 <nil>

$ ./reqrep node1 $url
NODE1: SENDING DATE REQUEST 2017-12-19T19:44:12+02:00
NODE1: RECEIVED DATE Tue Dec 19 19:44:12 2017

```

**Comment by gdamore** [comment] 2017-12-20 18:05
This can happen with REQ/REP if a message cannot be delivered for some
reason — REQ automatically retries until it gets a single reply.  REQ is
supposed to be idempotent, so this should be harmless.

**Comment by mrLSD** [comment] 2017-12-20 20:12
Not sure that I clearly understand when you see " message cannot be delivered" in my example.

Looks like similar to: #298

**Comment by gdamore** [comment] 2017-12-25 18:53
Yes, this is a duplicate of #298; closing.

**Closed by gdamore** 2017-12-25 18:53 UTC
